[package]
name = "regexperf_rs"
version = "0.1.0"
authors = ["William Saar <william@saar.se>"]

[dependencies]
regex = { git = "https://github.com/saarw/regex", branch = "threadunsafe-perf" }
time = "0.1.37"
